GET http://localhost:8080/hw68/api/students
Accept: application/json

###
GET http://localhost:8080/hw68/api/students/1
Accept: application/json

###
DELETE http://localhost:8080/hw68/api/students/1
Accept: application/json

###
POST http://localhost:8080/hw68/api/students
Content-Type: application/json

{
  "firstName": "Паша",
  "lastName": "Вишнев",
  "age": 35,
  "group": "Api"
}

###
PUT http://localhost:8080/hw68/api/students/1
Content-Type: application/json

{
  "firstName": "Вася",
  "lastName": "Вишнев",
  "age": 40,
  "group": "вфів"
}

###